### ISSUE TITLE
writeString length is always writed as big endian

### ISSUE THREAD

**Issue by fidovo** [tianhe1986/FatBinaryBuffer#1]
Hi, thanx fo your, lib. But i think in this part of code is string always writed as BE not LE.

In method: writeString is secondary parameter in writeUInt32 always true

`$length = strlen($val);`
`return $this->writeUInt32($length, true)->writeStringByLength($val, $length);`

**Comment by tianhe1986** [comment]
@fidovo Sure, you are right :)
 Could you create a pull request for it ? Just adding param `$isBigEndian` for `writeString` and  `readString`.

**Comment by fidovo** [comment]
@tianhe1986 I can try it maybe this week. :)

**Comment by fidovo** [comment]
Created in PR
https://github.com/tianhe1986/FatBinaryBuffer/pull/2

**Comment by fidovo** [comment]
resolved
